name: Back-End CI/CD

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login on my docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}   
      
      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            tmatteo99/url-health-monitor:latest
            tmatteo99/url-health-monitor:${{ github.sha }}
      - name: Update Infrastructure Repo
        env:
          INFRA_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}
        run: |
          git config --global user.email "matteo.torchia64@gmail.com"
          git config --global user.name "Github Actions"

          git clone https://x-access-token:${INFRA_TOKEN}@github.com/TMaTTeO99/health-monitor-infra.git
          cd health-monitor-infra

          sed -i "s|image: tmatteo99/url-health-monitor:.*|image: tmatteo99/url-health-monitor:${{ github.sha }}|g" app-deployment.yaml

          git add .
          git commit -m "chore: update backend image to ${{ github.sha }}"
          git push